using System.Collections.Immutable;

namespace _07.Models;

/// <summary>
/// Represents a shell command.
/// </summary>
/// <param name="InputCommand">The executed command.</param>
/// <param name="Output">The output generated by the command, separated in lines.</param>
internal sealed record Command(string InputCommand, ImmutableArray<string> Output);